In [2]:
# Import dependencies
import pandas as pd
import numpy as np
pd.set_option('max_colwidth', 400)

### Extract the crowdfunding.xlsx Data

In [ ]:
# Read the data into a Pandas DataFrame
crowdfunding_info_df = pd.read_excel('Resources/crowdfunding.xlsx')
crowdfunding_info_df.head()

In [ ]:
# Get a brief summary of the crowdfunding_info DataFrame.
shape_df = crowdfunding_info_df.shape #(1000, 15)
len(crowdfunding_info_df)
brief_summary_dtypes = crowdfunding_info_df.dtypes.array
index_columns = crowdfunding_info_df.columns.array
notnullcountrows = crowdfunding_info_df.count().array
brief_summary_dtypes
index_columns
concat_notnull = []
for i in notnullcountrows:
    if len(concat_notnull) < 15 or len(concat_notnull) == 0:
        concat_notnull.append(f"{i} non-null")
    elif len(concat_notnull == 15):
        break;
    elif len(concat_notnull >15):
            concat_notnull = concat_notnull.iloc[0:16]
    else:
        concat_notnull = concat_notnull.iloc[0:16]
    
concat_notnull

In [ ]:
type(crowdfunding_info_df.shape)
for i in range(len(crowdfunding_info_df.shape)):
    rows = crowdfunding_info_df.shape[0]
    columns = crowdfunding_info_df.shape[1]
index_columns

In [ ]:
print(type(crowdfunding_info_df))
print(crowdfunding_info_df.memory_usage(index = False, deep = True))
print(f"rangeIndex: {rows} 0 to 999")
print(f"Data columns (total {columns} columns):")
df = pd.DataFrame({"Column":index_columns, "Non-Null Count":concat_notnull, "Dtype":brief_summary_dtypes })
df

### Create the Category and Subcategory DataFrames
---
**Create a Category DataFrame that has the following columns:**
* A "category_id" column that has entries going sequentially from "cat1" to "cat*n*", where *n* is the number of unique categories
* A "category" column that contains only the category titles

Export the DataFrame as a `category.csv` CSV file.

**Create a SubCategory DataFrame that has the following columns:**
* A "subcategory_id" column that has entries going sequentially from "subcat1" to "subcat*n*", where *n* is the number of unique subcategories
* A "subcategory" column that contains only the subcategory titles

Export the DataFrame as a `subcategory.csv` CSV file.

In [ ]:
# Get the crowdfunding_info_df columns.
crowdfunding_info_df.rename(columns={'category & sub-category':'category/sub-category'}, inplace = True)
crowdfunding_info_df.columns

In [ ]:
# Assign the category and subcategory values to category and subcategory columns.
crowdfunding_info_df[['category', 'sub-category']] = crowdfunding_info_df['category/sub-category'].str.split('/', expand = True)
crowdfunding_info_df.head()

In [ ]:
# Get the unique categories and subcategories in separate lists.
categories = pd.Series(crowdfunding_info_df.iloc[: ,-2].to_list()).unique()
subcategories = pd.Series(crowdfunding_info_df.iloc[: ,-1].to_list()).unique()

print(categories)
print(subcategories)

In [ ]:
# Get the number of distinct values in the categories and subcategories lists.

print(len(categories))
print(len(subcategories))

In [ ]:
# Create numpy arrays from 1-9 for the categories and 1-24 for the subcategories.
category_ids = np.arange(1, 10)
subcategory_ids = np.arange(1, 25)

print(category_ids)
print(subcategory_ids)

In [ ]:
# Use a list comprehension to add "cat" to each category_id. 
cat_ids=["cat"+str(i) for i in category_ids if i<10]
# Use a list comprehension to add "subcat" to each subcategory_id.    
scat_ids = ["subcat"+str(k) for k in subcategory_ids if k <=24]
    
print(cat_ids)
print(scat_ids)

In [ ]:
# Create a category DataFrame with the category_id array as the category_id and categories list as the category name.
category_df = pd.DataFrame({"category_id":cat_ids, "category":categories})
# Create a category DataFrame with the subcategory_id array as the subcategory_id and subcategories list as the subcategory name. 
subcategory_df = pd.DataFrame({"subcategory_id":scat_ids, "subcategory":subcategories})

In [ ]:
category_df

In [ ]:
subcategory_df

In [ ]:
# Export categories_df and subcategories_df as CSV files.
category_df.to_csv("Resources/category.csv", index=False)

subcategory_df.to_csv("Resources/subcategory.csv", index=False)

### Campaign DataFrame
----
**Create a Campaign DataFrame that has the following columns:**
- The "cf_id" column.
- The "contact_id" column.
- The “company_name” column.
- The "blurb" column is renamed as "description."
- The "goal" column.
- The "goal" column is converted to a `float` datatype.
- The "pledged" column is converted to a `float` datatype. 
- The "backers_count" column. 
- The "country" column.
- The "currency" column.
- The "launched_at" column is renamed as "launch_date" and converted to a datetime format. 
- The "deadline" column is renamed as "end_date" and converted to a datetime format.
- The "category_id" with the unique number matching the “category_id” from the category DataFrame. 
- The "subcategory_id" with the unique number matching the “subcategory_id” from the subcategory DataFrame.
- And, create a column that contains the unique four-digit contact ID number from the `contact.xlsx` file.
 

Then export the DataFrame as a `campaign.csv` CSV file.

In [ ]:
# Create a copy of the crowdfunding_info_df DataFrame name campaign_df. 
campaign_df = crowdfunding_info_df.copy()
campaign_df.head()

In [ ]:
# Rename the blurb, launched_at, and deadline columns.
campaign_df.rename(columns={'blurb':'description', 'launched_at':'launched_date', 'deadline':'end_date'},inplace = True)
campaign_df.dtypes

In [ ]:
# Convert the goal and pledged columns to a `float` data type.
campaign_df['goal'] = campaign_df['goal'].astype('float64')
campaign_df['pledged'] = campaign_df['pledged'].astype('float64')
campaign_df.head()

In [ ]:
# Check the datatypes
campaign_df.dtypes

In [ ]:
# Format the launched_date and end_date columns to datetime format
from datetime import datetime as dt

campaign_df['launched_date']= pd.to_datetime(campaign_df['launched_date'], unit ='s')

campaign_df['end_date'] = pd.to_datetime(campaign_df['end_date'], unit = 's')

campaign_df.head(5)

In [ ]:
# Merge the campaign_df with the category_df on the "category" column and 
# the subcategory_df on the "subcategory" column.
campaign_cat_df = campaign_df.merge(category_df,'inner','category')
subcategory_df.rename(columns={'subcategory':'sub-category'}, inplace = True)
campaign_merged_df = campaign_cat_df.merge(subcategory_df, 'outer', on='sub-category')
campaign_merged_df.tail(10)

In [ ]:
# Drop unwanted columns
drop_columns=["category/sub-category","category","sub-category"]
for i in range(0,len(drop_columns)):
    num_columns = campaign_merged_df.columns.array
    for k in range(0, len(num_columns)):
        if num_columns[k] == drop_columns[i]:
            pd.DataFrame(campaign_merged_df.drop(columns=drop_columns[i], axis ='columns')) 
            
        else:
            print("column not found")
            break;
campaign_cleaned = campaign_merged_df.rename({'cf_id':'cf_id', 'contact_id':'contact_id','description':'description', 'goal':'goal', 'pledged':'pledged','outcome': 'outcome','backers_count':'backers_count', 'country':'country','currency':'currency','launched_date':'launched_date','end_date':'end_date', 'staff_pick':'staff_pick', 'spotlight':'spotlight','category_id':'category_id','subcategory_id':'subcategory_id'})  
campaign_cleaned.head()

In [ ]:
# Export the DataFrame as a CSV file. 
campaign_cleaned.to_csv("Resources/campaign.csv", index=False)

### Extract the contacts.xlsx Data.

In [3]:
# Read the data into a Pandas DataFrame. Use the `header=2` parameter when reading in the data.
contact_info_df = pd.read_excel('Resources/contacts.xlsx', header=2)
contact_info_df.head()

0                                                                               contact_info
1   {"contact_id": 4661, "name": "Cecilia Velasco", "email": "cecilia.velasco@rodrigues.fr"}
2          {"contact_id": 3765, "name": "Mariana Ellis", "email": "mariana.ellis@rossi.org"}
3            {"contact_id": 4187, "name": "Sofie Woods", "email": "sofie.woods@riviere.com"}
4  {"contact_id": 4941, "name": "Jeanette Iannotti", "email": "jeanette.iannotti@yahoo.com"}

### Create the Contacts DataFrame 
---
**Create a Contacts DataFrame that has the following columns:**
- A column named "contact_id"  that contains the unique number of the contact person.
- A column named "first_name" that contains the first name of the contact person.
- A column named "last_name" that contains the first name of the contact person.
- A column named "email" that contains the email address of the contact person

Then export the DataFrame as a `contacts.csv` CSV file.

### Option 1: Use Pandas to create the contacts DataFrame.

In [4]:
# Iterate through the contact_info_df and convert each row to a dictionary.
from json import loads, dumps
import ast
c = []
row1 = []

new_dict = {}
results = contact_info_df.to_json(orient="table")
parsed = loads(results)
dfjson=dumps(parsed, indent=4)
df = pd.read_json(dfjson, orient="table")
for index, row in df.iterrows():
    c.append(list(row))
for ind, row in enumerate(c):
    for j in range(1, 1001):
        row1.append(ast.literal_eval(c[j][0]))

In [5]:
list_values = []
for i in row1:
    for key, value in i.items():
        list_values.append(value)
list_values

[4661,
 'Cecilia Velasco',
 'cecilia.velasco@rodrigues.fr',
 3765,
 'Mariana Ellis',
 'mariana.ellis@rossi.org',
 4187,
 'Sofie Woods',
 'sofie.woods@riviere.com',
 4941,
 'Jeanette Iannotti',
 'jeanette.iannotti@yahoo.com',
 2199,
 'Samuel Sorgatz',
 'samuel.sorgatz@gmail.com',
 5650,
 'Socorro Luna',
 'socorro.luna@hotmail.com',
 5889,
 'Carolina Murray',
 'carolina.murray@knight.com',
 4842,
 'Kayla Moon',
 'kayla.moon@yahoo.de',
 3280,
 'Ariadna Geisel',
 'ariadna.geisel@rangel.com',
 5468,
 'Danielle Ladeck',
 'danielle.ladeck@scalfaro.net',
 3064,
 'Tatiana Thompson',
 'tatiana.thompson@hunt.net',
 4904,
 'Caleb Benavides',
 'caleb.benavides@rubio.com',
 1299,
 'Sandra Hardy',
 'sandra.hardy@web.de',
 5602,
 'Lotti Morris',
 'lotti.morris@yahoo.co.uk',
 5753,
 'Reinhilde White',
 'reinhilde.white@voila.fr',
 4495,
 'Kerry Patel',
 'kerry.patel@hutchinson.com',
 4269,
 'Sophie Antoine',
 'sophie.antoine@andersen.com',
 2226,
 'Martha Girard',
 'martha.girard@web.de',
 1558,
 'Stephanie King',
 'stephanie.king@cervantes.com',
 2307,
 'Amanda Palmer',
 'amanda.palmer@didier.fr',
 2900,
 'Lina Alcala',
 'lina.alcala@vespa.net',
 5695,
 'Itzel Murphy',
 'itzel.murphy@muelichen.de',
 5708,
 'Filippo Parry',
 'filippo.parry@live.com',
 1663,
 'Katelyn Cole',
 'katelyn.cole@fiebig.com',
 3605,
 'Brian Novak',
 'brian.novak@ford.net',
 4678,
 'Cilly Gay',
 'cilly.gay@callegaro.it',
 2251,
 'Yolanda Snyder',
 'yolanda.snyder@gmx.de',
 6202,
 'Evelin Odonnell',
 'evelin.odonnell@ibarra.net',
 3715,
 'Ingeborg Alba',
 'ingeborg.alba@hotmail.com',
 4242,
 'Marina Madrid',
 'marina.madrid@galarza-alba.com',
 4326,
 'Sheila Goodwin',
 'sheila.goodwin@yahoo.com',
 5560,
 'Valeria Rich',
 'valeria.rich@turchetta-mondadori.it',
 4002,
 'Dustin Camacho',
 'dustin.camacho@rhodes.org.au',
 3813,
 'Amalia Marenzio',
 'amalia.marenzio@grupo.com',
 5336,
 'Gian Long',
 'gian.long@hotmail.com',
 4994,
 'Stewart Hunt',
 'stewart.hunt@anderson-vargas.biz',
 1471,
 'Greca Ruiz',
 'greca.ruiz@carr.co.uk',
 4482,
 'Gerald Olivera',
 'gerald.olivera@outlook.com',
 3241,
 'Jaqueline Wallace',
 'jaqueline.wallace@gmail.com',
 3477,
 'John Lane',
 'john.lane@gregoire.fr',
 2265,
 'Pero Joly',
 'pero.joly@bernard.net',
 5911,
 'Chad Turner',
 'chad.turner@gmail.com',
 2288,
 'Adam Zavala',
 'adam.zavala@guichard.fr',
 4064,
 'Tyler Rivera',
 'tyler.rivera@guajardo-ozuna.com',
 1294,
 'Jens Graham',
 'jens.graham@jones-buckley.com',
 5008,
 'Virginia Caetani',
 'virginia.caetani@sosa.biz',
 3604,
 'Martino Wagner',
 'martino.wagner@laposte.net',
 3263,
 'Martin Meyer',
 'martin.meyer@davis.co.uk',
 5631,
 'Marguerite Walls',
 'marguerite.walls@martinez.fr',
 2851,
 'Peter Vogt',
 'peter.vogt@yahoo.com',
 3714,
 'Nicholas Christian',
 'nicholas.christian@hotmail.de',
 1664,
 'Susi Steinberg',
 'susi.steinberg@preiss.com',
 5027,
 'Tammy Ramazzotti',
 'tammy.ramazzotti@gmail.com',
 3070,
 'Abdul Thomas',
 'abdul.thomas@vasari.com',
 4248,
 'Justin Luxardo',
 'justin.luxardo@googlemail.com',
 2034,
 'Antonio Gibson',
 'antonio.gibson@faust.net',
 4085,
 'Jeremy Gomez',
 'jeremy.gomez@oconnor.org',
 3569,
 'Raymond Solorzano',
 'raymond.solorzano@gmail.com',
 3889,
 'Flora Harris',
 'flora.harris@hotmail.com.au',
 3136,
 'Cheryl Boyd',
 'cheryl.boyd@segni.it',
 2103,
 'Rhys Leiva',
 'rhys.leiva@gmx.de',
 2329,
 'Mariano Prieto',
 'mariano.prieto@vodafone.it',
 3325,
 'Laurie Fibonacci',
 'laurie.fibonacci@gmail.com',
 3131,
 'David Rudolph',
 'david.rudolph@nelson.com',
 4995,
 'Bryan Ross',
 'bryan.ross@yahoo.com',
 3631,
 'Ubaldo Brown',
 'ubaldo.brown@philippe.com',
 5373,
 'Clelia Faulkner',
 'clelia.faulkner@hotmail.com',
 3126,
 'Sara Erickson',
 'sara.erickson@yahoo.de',
 2194,
 'Rupert Valle',
 'rupert.valle@filogamo.it',
 2906,
 'Puccio Kitzmann',
 'puccio.kitzmann@yahoo.com',
 2611,
 'Thomas Hutchinson',
 'thomas.hutchinson@gmx.de',
 2374,
 'Abelardo Castro',
 'abelardo.castro@gmail.com',
 3254,
 'Greco Walker',
 'greco.walker@yahoo.com',
 3571,
 'Miranda Lacombe',
 'miranda.lacombe@longoria-vanegas.net',
 2812,
 'Diana Schuchhardt',
 'diana.schuchhardt@libero.it',
 3961,
 'Stacey Knox',
 'stacey.knox@corporacin.com',
 3872,
 'Glen Faivre',
 'glen.faivre@yahoo.com',
 4736,
 'Andrew Torres',
 'andrew.torres@ruiz-torres.org',
 5119,
 'Denny Fritz',
 'denny.fritz@despacho.biz',
 5725,
 'Martyn Caldera',
 'martyn.caldera@hotmail.co.uk',
 4037,
 'Abigail Foster',
 'abigail.foster@taylor.net',
 2109,
 'Anthony Hauffer',
 'anthony.hauffer@tlustek.org',
 3283,
 'Roger Gerlach',
 'roger.gerlach@may-mitchell.co.uk',
 6181,
 'Christopher Poirier',
 'christopher.poirier@hotmail.com',
 3251,
 'Branka Traore',
 'branka.traore@jacobi.com',
 3443,
 'Briana Etienne',
 'briana.etienne@bishop-coates.com',
 2988,
 'Brandon Olson',
 'brandon.olson@prince-moreno.net',
 1673,
 'Celia Ungaretti',
 'celia.ungaretti@fox.com',
 2085,
 'Barbara Guibert',
 'barbara.guibert@casares-sanches.com',
 1672,
 'Daniela Bell',
 'daniela.bell@vollbrecht.org',
 4426,
 'Phyllis Gurule',
 'phyllis.gurule@rodriguez-pham.com',
 3211,
 'Alejandra Joseph',
 'alejandra.joseph@escalante-abrego.biz',
 3190,
 'Giulio Bohlander',
 'giulio.bohlander@dbmail.com',
 2081,
 'Amber Weller',
 'amber.weller@toso.eu',
 3185,
 'Mary Etzold',
 'mary.etzold@conrad-harrison.com',
 5044,
 'Amy Georges',
 'amy.georges@raedel.de',
 1883,
 'Jennifer Giraud',
 'jennifer.giraud@yahoo.com',
 2067,
 'Rosie Peltier',
 'rosie.peltier@voila.fr',
 4604,
 'Oreste Ward',
 'oreste.ward@proyectos.com',
 3203,
 'Luis Edwards',
 'luis.edwards@live.com',
 5758,
 'Fiona Griffiths',
 'fiona.griffiths@curatoli-verdone.it',
 5755,
 'Sally Raya',
 'sally.raya@tarchetti.it',
 5150,
 'Carolyn Charpentier',
 'carolyn.charpentier@hotmail.de',
 4181,
 'Nathalie Alvarez',
 'nathalie.alvarez@live.com',
 3006,
 'Abril Lowery',
 'abril.lowery@novak.net',
 4865,
 'Ottone Sullivan',
 'ottone.sullivan@hussain-kaur.com',
 2862,
 'Esmeralda Sollima',
 'esmeralda.sollima@visintini.it',
 6070,
 'Silvia Gierschner',
 'silvia.gierschner@tele2.it',
 5300,
 'Kyle Cunningham',
 'kyle.cunningham@voila.fr',
 3486,
 'Anel Carpentier',
 'anel.carpentier@klein-joseph.org',
 5989,
 'Sarah Davis',
 'sarah.davis@david.com',
 2849,
 'Luke Klein',
 'luke.klein@hotmail.com',
 1612,
 'Gudrun Mueller',
 'gudrun.mueller@dillon-fuller.info',
 3307,
 'Melissa Canali',
 'melissa.canali@libero.it',
 5288,
 'Gabrielle Ayala',
 'gabrielle.ayala@hotmail.com',
 6026,
 'Laura Buckley',
 'laura.buckley@ryan.org',
 2212,
 'Wilfrido Lorch',
 'wilfrido.lorch@leclerc.fr',
 4591,
 'Robert Bruder',
 'robert.bruder@manzoni.com',
 2771,
 'Phillip Soliz',
 'phillip.soliz@outlook.com',
 5682,
 'Alex Smith',
 'alex.smith@fournier.fr',
 5368,
 'Jessica Martinez',
 'jessica.martinez@salieri.com',
 3706,
 'Kelly Carter',
 'kelly.carter@hotmail.com.au',
 4034,
 'Ahmad Sosa',
 'ahmad.sosa@gmail.com',
 3209,
 'Toralf Iglesias',
 'toralf.iglesias@borrego.com',
 2384,
 'Irene Anichini',
 'irene.anichini@yahoo.com',
 3074,
 'Alicia Cainero',
 'alicia.cainero@yahoo.com',
 2031,
 'Tracey Laboy',
 'tracey.laboy@bell.biz',
 5873,
 'Donald Reynaud',
 'donald.reynaud@green.edu.au',
 5501,
 'Venancio Stadelmann',
 'venancio.stadelmann@gmx.de',
 3489,
 'Seth Olivier',
 'seth.olivier@yahoo.com',
 4210,
 'Dennis Boaga',
 'dennis.boaga@gmx.de',
 6151,
 'Pedro Wilson',
 'pedro.wilson@outlook.com',
 6047,
 'Roland Weihmann',
 'roland.weihmann@gmail.com',
 5445,
 'Hector Morrison',
 'hector.morrison@web.de',
 5493,
 'Evangelos Peters',
 'evangelos.peters@sanchez.net',
 6036,
 'Gerardo Hamilton',
 'gerardo.hamilton@libero.it',
 2368,
 'Meta Cuzzocrea',
 'meta.cuzzocrea@howard-jensen.org',
 1501,
 'Alma Raymond',
 'alma.raymond@tin.it',
 4351,
 'Kathleen Solimena',
 'kathleen.solimena@wallace.biz',
 3096,
 'Zacharie Cordier',
 'zacharie.cordier@gmail.com',
 6162,
 'Riza Techer',
 'riza.techer@yahoo.com',
 1433,
 'Enrique Guillen',
 'enrique.guillen@hotmail.co.uk',
 2720,
 'Tristan Weeks',
 'tristan.weeks@pena.com',
 5251,
 'Natalie Lerma',
 'natalie.lerma@boucher.com',
 1797,
 'Rodney Hamon',
 'rodney.hamon@hotmail.com',
 1656,
 'Adalberto Lombardo',
 'adalberto.lombardo@sfr.fr',
 1346,
 'Florencia Querini',
 'florencia.querini@gmail.com',
 2989,
 'Liam Rolland',
 'liam.rolland@yahoo.fr',
 5629,
 'Ian Kelly',
 'ian.kelly@reeves.com.au',
 3456,
 'Mehdi Todd',
 'mehdi.todd@web.de',
 3229,
 'Rembrandt Liguori',
 'rembrandt.liguori@davis.org',
 2277,
 'Irmi Schweitzer',
 'irmi.schweitzer@ozuna.com',
 1276,
 'Gioffre Stein',
 'gioffre.stein@hotmail.com.au',
 3694,
 'Frida Villarreal',
 'frida.villarreal@hotmail.de',
 2260,
 'Steffen Mangold',
 'steffen.mangold@paul.net',
 5374,
 'Elias Marin',
 'elias.marin@herve.net',
 4420,
 'Roman Gonzalez',
 'roman.gonzalez@anderson.net',
 3849,
 'Reina Middleton',
 'reina.middleton@hotmail.com',
 1638,
 'Sandro Moran',
 'sandro.moran@hotmail.de',
 5230,
 'Gebhard Thanel',
 'gebhard.thanel@gmail.com',
 1763,
 'Antonino Bolander',
 'antonino.bolander@gmail.com',
 4323,
 'Karl Trevisani',
 'karl.trevisani@anguissola.it',
 5256,
 'Silvester Brookes',
 'silvester.brookes@franco.org',
 4836,
 'Octavio Pratt',
 'octavio.pratt@web.de',
 5981,
 'Rebecca Greer',
 'rebecca.greer@hotmail.com',
 1463,
 'Pierina Gaggini',
 'pierina.gaggini@free.fr',
 4577,
 'Robin Schleich',
 'robin.schleich@rogers-barrera.biz',
 4951,
 'Sergio Abbott',
 'sergio.abbott@moore.net.au',
 3567,
 'Gilberto Evans',
 'gilberto.evans@salcedo-archuleta.net',
 5475,
 'James Elliott',
 'james.elliott@gmail.com',
 2114,
 'Timoteo Bolnbach',
 'timoteo.bolnbach@laboratorios.com',
 5216,
 'Tonino Stanley',
 'tonino.stanley@hotmail.com',
 1665,
 'Margaretha Murialdo',
 'margaretha.murialdo@meunier.com',
 6051,
 'Bianca Drubin',
 'bianca.drubin@libero.it',
 3983,
 'Kaylee Hoffmann',
 'kaylee.hoffmann@poulain.com',
 2966,
 'Teresa Vecellio',
 'teresa.vecellio@yahoo.com',
 4478,
 'Emine Tacchini',
 'emine.tacchini@dbmail.com',
 4238,
 'Dawn Cortez',
 'dawn.cortez@gmail.com',
 4404,
 'Emily Cundari',
 'emily.cundari@clark.com.au',
 5666,
 'Eleanor Hall',
 'eleanor.hall@hotmail.com',
 3691,
 'Monique Delgadillo',
 'monique.delgadillo@hotmail.co.uk',
 2703,
 'Arnaude Warner',
 'arnaude.warner@gmail.com',
 4253,
 'Jason Howell',
 'jason.howell@gmx.de',
 5652,
 'Nicole Mccullough',
 'nicole.mccullough@hall.com',
 3279,
 'Rosmarie Esquibel',
 'rosmarie.esquibel@bouygtel.fr',
 3233,
 'Leonor Ferreira',
 'leonor.ferreira@gmail.com',
 3017,
 'Brett Jones',
 'brett.jones@alice.it',
 3482,
 'Nino Bien',
 'nino.bien@gmail.com',
 2166,
 'Jemma Tate',
 'jemma.tate@hotmail.de',
 4146,
 'Denis Rogers',
 'denis.rogers@poste.it',
 2651,
 'Vanesa Khan',
 'vanesa.khan@voila.fr',
 1409,
 'Victoria Ojeda',
 'victoria.ojeda@doehn.com',
 3717,
 'Eugenio Martin',
 'eugenio.martin@yahoo.de',
 3963,
 'Nancy Hayes',
 'nancy.hayes@hotmail.com',
 2152,
 'Lara Jacob',
 'lara.jacob@buckley.org',
 2974,
 'Gino Hernandez',
 'gino.hernandez@covarrubias.com',
 1268,
 'Vicente Tijerina',
 'vicente.tijerina@montanariello.com',
 1822,
 'Michele Brambilla',
 'michele.brambilla@yahoo.com',
 5066,
 'Dana Ritacca',
 'dana.ritacca@gmail.com',
 5075,
 'Mitchell Bachmann',
 'mitchell.bachmann@suarez-cruz.com',
 3855,
 'Vincenza Key',
 'vincenza.key@adams.com',
 5923,
 'Salvador Gaillard',
 'salvador.gaillard@yahoo.de',
 1867,
 'Diane Rogner',
 'diane.rogner@kelly.co.uk',
 4376,
 'Josette Laine',
 'josette.laine@saracino-parisi.net',
 2785,
 'Courtney Fiebig',
 'courtney.fiebig@doerschner.com',
 5884,
 'Hugues Oliver',
 'hugues.oliver@stiffel.com',
 2441,
 'Espartaco Willis',
 'espartaco.willis@hotmail.com',
 1243,
 'Flavia Yoder',
 'flavia.yoder@hotmail.de',
 3411,
 'Casey Flores',
 'casey.flores@baggio.org',
 2467,
 'Calogero Cross',
 'calogero.cross@mercantini.it',
 1850,
 'Charles Begum',
 'charles.begum@laboratorios.info',
 2604,
 'Adina Pollard',
 'adina.pollard@outlook.com',
 1693,
 'Natasha Lara',
 'natasha.lara@outlook.com',
 2969,
 'Benita Pottier',
 'benita.pottier@sfr.fr',
 1544,
 'Elizabeth Valdivia',
 'elizabeth.valdivia@gmail.com',
 4149,
 'Mattia Huet',
 'mattia.huet@aol.de',
 3463,
 'Geza Howard',
 'geza.howard@voila.fr',
 2939,
 'Lauren Guillaume',
 'lauren.guillaume@sorgatz.org',
 2202,
 'Joanna Baxter',
 'joanna.baxter@bruce-wright.com',
 1728,
 'Tracy Metz',
 'tracy.metz@bryant.info',
 5362,
 'Birgit Pena',
 'birgit.pena@armellini.it',
 4840,
 'Elvira Papafava',
 'elvira.papafava@ifrance.com',
 2955,
 'Ernest Delorme',
 'ernest.delorme@dowerg.de',
 5354,
 'Christy Grossi',
 'christy.grossi@alarcon-tafoya.com',
 3847,
 'Hermelinda Olmos',
 'hermelinda.olmos@portillo.com',
 3025,
 'Herbert Fraser',
 'herbert.fraser@holloway.org.au',
 1615,
 'Giancarlo Heydrich',
 'giancarlo.heydrich@hotmail.com',
 5154,
 'Constance Maldonado',
 'constance.maldonado@spiess.net',
 5005,
 'Giampiero Carlier',
 'giampiero.carlier@hotmail.com',
 1349,
 'Carlo Jacquot',
 'carlo.jacquot@hotmail.com',
 3670,
 'Gabriel Robles',
 'gabriel.robles@yahoo.com',
 2912,
 'Gerd Gunpf',
 'gerd.gunpf@gmail.com',
 4336,
 'Ashley Hellwig',
 'ashley.hellwig@libero.it',
 5576,
 'Patrick Rosas',
 'patrick.rosas@yahoo.com',
 2736,
 'Lilla Leonard',
 'lilla.leonard@jungfer.com',
 3321,
 'Tony Nicolas',
 'tony.nicolas@morrocco-seddio.net',
 3353,
 'Allegra Benedetti',
 'allegra.benedetti@miller.com',
 2336,
 'Camille Tafuri',
 'camille.tafuri@aol.de',
 4369,
 'Juan Wheeler',
 'juan.wheeler@gilmore.net',
 4464,
 'Leopoldo Johnson',
 'leopoldo.johnson@hotmail.com.au',
 5626,
 'Dietmar Grenier',
 'dietmar.grenier@tele2.it',
 1669,
 'Leonid Scholl',
 'leonid.scholl@collin.com',
 5544,
 'Olivie Contarini',
 'olivie.contarini@marshall-wright.biz',
 6078,
 'Jeffery Lacroix',
 'jeffery.lacroix@medina.org',
 2580,
 'Edeltraud Chavez',
 'edeltraud.chavez@hotmail.com.au',
 3592,
 'Mesut Morvan',
 'mesut.morvan@gmail.com',
 4914,
 'Gregory Jackson',
 'gregory.jackson@ortiz.com',
 3848,
 'Nicola Rossi',
 'nicola.rossi@berry.org',
 2619,
 'Eddie Collazo',
 'eddie.collazo@gmail.com',
 4605,
 'Philippe Gardner',
 'philippe.gardner@howells-jones.net',
 6147,
 'Roy Fox',
 'roy.fox@tejeda.com',
 1383,
 'Heiderose Garcia',
 'heiderose.garcia@noos.fr',
 1757,
 'Claudine Rowley',
 'claudine.rowley@industrias.com',
 4390,
 'Astrid Roht',
 'astrid.roht@fastwebnet.it',
 4165,
 'Auguste Burnett',
 'auguste.burnett@yahoo.fr',
 4529,
 'Pellegrino Allen',
 'pellegrino.allen@gmail.com',
 6084,
 'Angela Bowers',
 'angela.bowers@laboratorios.com',
 2916,
 'Michael Descamps',
 'michael.descamps@gmail.com',
 2005,
 'Heidelore Kennedy',
 'heidelore.kennedy@guinizzelli.org',
 2261,
 'Lucrezia Koch',
 'lucrezia.koch@petit.com',
 5342,
 'Ivan Accardo',
 'ivan.accardo@web.de',
 4087,
 'Karen Avogadro',
 'karen.avogadro@yahoo.com',
 2761,
 'Laetitia Gallet',
 'laetitia.gallet@aubry.org',
 2908,
 'Amico Gosselin',
 'amico.gosselin@shaw.info',
 2155,
 'Ilaria Bowen',
 'ilaria.bowen@hotmail.it',
 5642,
 'Marlen Coardi',
 'marlen.coardi@colletti.eu',
 6217,
 'Rafael Alexander',
 'rafael.alexander@jenkins.com',
 4222,
 'Herma Gabbana',
 'herma.gabbana@hotmail.com',
 4798,
 'Zachary Vespucci',
 'zachary.vespucci@industrias.com',
 5660,
 'Marisol Richard',
 'marisol.richard@gmail.com',
 5000,
 'Joseph Glover',
 'joseph.glover@laposte.net',
 2809,
 'Lauretta Neal',
 'lauretta.neal@hotmail.de',
 3349,
 'Simone Sauvage',
 'simone.sauvage@yahoo.com',
 3647,
 'Ramona Brooks',
 'ramona.brooks@kensy.de',
 5745,
 'Gioele Schwital',
 'gioele.schwital@moody.com',
 2583,
 'Elena Jimenez',
 'elena.jimenez@yahoo.com.au',
 5441,
 'Pam Vargas',
 'pam.vargas@guillot.net',
 2090,
 'Alison Morales',
 'alison.morales@lewis.com',
 3386,
 'Marc Aumann',
 'marc.aumann@holland.com',
 1816,
 'Carla Butler',
 'carla.butler@yahoo.com',
 4718,
 'Dionigi Bruce',
 'dionigi.bruce@industrias.com',
 1677,
 'Frank Henry',
 'frank.henry@yahoo.com',
 4218,
 'Brent Pons',
 'brent.pons@proyectos.net',
 4548,
 'Patricia Liebelt',
 'patricia.liebelt@baca.org',
 1431,
 'Micheletto Sykes',
 'micheletto.sykes@thompson-thompson.com',
 2830,
 'Rose Blanc',
 'rose.blanc@grupo.com',
 4400,
 'Vincent Singh',
 'vincent.singh@gmail.com',
 5773,
 'Jamie Peacock',
 'jamie.peacock@interiano-nordio.com',
 4161,
 'Giorgia Dijoux',
 'giorgia.dijoux@paul.com',
 2062,
 'Serena Piacentini',
 'serena.piacentini@yahoo.de',
 3458,
 'Dimitri Posada',
 'dimitri.posada@gmail.com',
 3174,
 'Alexa Barillaro',
 'alexa.barillaro@ramos.net',
 5565,
 'Megan Kuhl',
 'megan.kuhl@despacho.com',
 1906,
 'Kaitlyn Farinelli',
 'kaitlyn.farinelli@outlook.com',
 5479,
 'Jonathan Castellitto',
 'jonathan.castellitto@libero.it',
 4320,
 'Lisa Terragni',
 'lisa.terragni@proyectos.com',
 4213,
 'Olivier Petrucelli',
 'olivier.petrucelli@letta-raurica.eu',
 3373,
 'Jos Trobbiani',
 'jos.trobbiani@samson.com',
 4184,
 'Mirjam Dawson',
 'mirjam.dawson@yahoo.com',
 5472,
 'Javier Tessier',
 'javier.tessier@mclaughlin.biz',
 5559,
 'Mirjana Collins',
 'mirjana.collins@hotmail.com',
 5419,
 'Vanessa Tschentscher',
 'vanessa.tschentscher@mitchell.com',
 4171,
 'Antonina Cobb',
 'antonina.cobb@gibson.org',
 1302,
 'Bernard Durand',
 'bernard.durand@royer.com',
 3520,
 'Corey Greggio',
 'corey.greggio@johnson.org.au',
 6010,
 'Rodolfo Couturier',
 'rodolfo.couturier@tim.it',
 4617,
 'Pierre Cardenas',
 'pierre.cardenas@luzi-bonomo.eu',
 1417,
 'Romeo Surian',
 'romeo.surian@batista.com',
 4770,
 'Ivo Moreno',
 'ivo.moreno@hotmail.com',
 4328,
 'Federico Marie',
 'federico.marie@jourdan.fr',
 5171,
 'Maggie Boito',
 'maggie.boito@yahoo.com',
 4394,
 'Brianna Hanson',
 'brianna.hanson@stanley.com',
 1794,
 'Heiko Bourgeois',
 'heiko.bourgeois@togliatti.com',
 3510,
 'Benito Gritti',
 'benito.gritti@gmail.com',
 2487,
 'Mitzy Junk',
 'mitzy.junk@zaragoza.com',
 2215,
 'Samantha Lowe',
 'samantha.lowe@praga.it',
 4136,
 'Ernesto Nerger',
 'ernesto.nerger@middleton.co.uk',
 3723,
 'Melinda Canova',
 'melinda.canova@orange.fr',
 5842,
 'Mohammad Hartung',
 'mohammad.hartung@hotmail.com',
 3289,
 'Ben Maillot',
 'ben.maillot@ramos.net',
 1249,
 'Isabel Pruschke',
 'isabel.pruschke@gmail.com',
 5409,
 'Linda Franceschi',
 'linda.franceschi@richards.net',
 2951,
 'Olivia Striebitz',
 'olivia.striebitz@gmail.com',
 3432,
 'Penny Watson',
 'penny.watson@matthews.net',
 2297,
 'Manfred James',
 'manfred.james@davies.org',
 6161,
 'Hazel Pierce',
 'hazel.pierce@outlook.com',
 4603,
 'Alf Bates',
 'alf.bates@dunn.com',
 5818,
 'Scott Gough',
 'scott.gough@industrias.com',
 4270,
 'Konrad Briones',
 'konrad.briones@fierro.com',
 6007,
 'Mathilde Kruschwitz',
 'mathilde.kruschwitz@yahoo.com',
 4084,
 'Irma Gemito',
 'irma.gemito@googlemail.com',
 1340,
 'Antoine Guyon',
 'antoine.guyon@yahoo.com',
 5675,
 'William Gibilisco',
 'william.gibilisco@gaillard.com',
 2010,
 ...]

In [9]:
# Create a contact_info DataFrame and add each list of values, i.e., each row 
# to the 'contact_id', 'name', 'email' columns.
columns = ['contact_id', 'name', 'email']
value_list = []
for l in range(0,len(list_values), 3):
    value_list.append(list_values[l:l+3])
print(value_list)    
contact_info_DataFrame = pd.DataFrame(value_list, columns = columns)
contact_info_DataFrame.tail(5)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

,contact_id,name,email
1000995,3684,Whitney Noack,whitney.noack@laboratorios.org
1000996,5784,Gelsomina Migliaccio,gelsomina.migliaccio@junk.com
1000997,1498,Evangelista Pereira,evangelista.pereira@thompson-peterson.biz
1000998,6073,Gareth Comolli,gareth.comolli@tiscali.fr
1000999,4939,Michelangelo Hess,michelangelo.hess@bouygtel.fr

In [7]:
# Check the datatypes.
contact_info_DataFrame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001000 entries, 0 to 1000999
Data columns (total 3 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   contact_id  1001000 non-null  int64
 1   name        1001000 non-null  object
 2   email       1001000 non-null  object
dtypes: int64(1), object(2)
memory usage: 22.9+ MB

In [10]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 
contact_info_DataFrame[['first_name','last_name']] = contact_info_DataFrame['name'].str.split(' ', expand=True)
# contact_info_df.head()

# Drop the contact_name column
contact_info_DataFrame.drop(columns = ['name'], inplace = True)
contact_info_DataFrame.head()

   contact_id                         email first_name last_name
0        4661  cecilia.velasco@rodrigues.fr    Cecilia   Velasco
1        3765       mariana.ellis@rossi.org    Mariana     Ellis
2        4187       sofie.woods@riviere.com      Sofie     Woods
3        4941   jeanette.iannotti@yahoo.com   Jeanette  Iannotti
4        2199      samuel.sorgatz@gmail.com     Samuel   Sorgatz

In [11]:
# Reorder the columns

contacts_df_clean = contact_info_DataFrame[['contact_id','first_name','last_name','email']]
contacts_df_clean.head()

   contact_id first_name last_name                         email
0        4661    Cecilia   Velasco  cecilia.velasco@rodrigues.fr
1        3765    Mariana     Ellis       mariana.ellis@rossi.org
2        4187      Sofie     Woods       sofie.woods@riviere.com
3        4941   Jeanette  Iannotti   jeanette.iannotti@yahoo.com
4        2199     Samuel   Sorgatz      samuel.sorgatz@gmail.com

In [12]:
# Check the datatypes one more time before exporting as CSV file.
contacts_df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1001000 entries, 0 to 1000999
Data columns (total 4 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   contact_id  1001000 non-null  int64
 1   first_name  1001000 non-null  object
 2   last_name   1001000 non-null  object
 3   email       1001000 non-null  object
dtypes: int64(1), object(3)
memory usage: 30.5+ MB

In [13]:
# Export the DataFrame as a CSV file. 
contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)

### Option 2: Use regex to create the contacts DataFrame.

In [16]:
contact_info_df_copy = contact_info_df.copy()
contact_info_df_copy.head()

contact_info_df_copy.reset_index()

,index,text
0,0,contact_info
1,1,"{""contact_id"": 4661, ""name"": ""Cecilia Velasco"", ""email"": ""cecilia.velasco@rodrigues.fr""}"
2,2,"{""contact_id"": 3765, ""name"": ""Mariana Ellis"", ""email"": ""mariana.ellis@rossi.org""}"
3,3,"{""contact_id"": 4187, ""name"": ""Sofie Woods"", ""email"": ""sofie.woods@riviere.com""}"
4,4,"{""contact_id"": 4941, ""name"": ""Jeanette Iannotti"", ""email"": ""jeanette.iannotti@yahoo.com""}"
...,...,...
996,996,"{""contact_id"": 3684, ""name"": ""Whitney Noack"", ""email"": ""whitney.noack@laboratorios.org""}"
997,997,"{""contact_id"": 5784, ""name"": ""Gelsomina Migliaccio"", ""email"": ""gelsomina.migliaccio@junk.com""}"
998,998,"{""contact_id"": 1498, ""name"": ""Evangelista Pereira"", ""email"": ""evangelista.pereira@thompson-peterson.biz""}"
999,999,"{""contact_id"": 6073, ""name"": ""Gareth Comolli"", ""email"": ""gareth.comolli@tiscali.fr""}"
1000,1000,"{""contact_id"": 4939, ""name"": ""Michelangelo Hess"", ""email"": ""michelangelo.hess@bouygtel.fr""}"

In [36]:
# Extract the four-digit contact ID number.
import re
contact_info_df_copy.columns = ['text']
p = r"\d{4}"
list_contact_id = []
dict_rows = contact_info_df_copy['text'].iloc[1:].array
for l in dict_rows:
    list_contact_id .append(re.findall(p, l))
list_contact_id 
contact_info_df_copy["contact_ID"] = list_contact_id 
contact_info_df_copy.head()

ValueError: Length of values (1000) does not match length of index (1001)

In [34]:
# Check the datatypes.
contact_info_df_copy.columns
contact_info_df_copy.dtypes

text    object
dtype: object

In [ ]:
# Convert the "contact_id" column to an int64 data type.

In [ ]:
# Extract the name of the contact and add it to a new column.

In [ ]:
# Extract the email from the contacts and add the values to a new column.

In [ ]:
# Create a copy of the contact_info_df with the 'contact_id', 'name', 'email' columns.

In [ ]:
# Create a "first"name" and "last_name" column with the first and last names from the "name" column. 


# Drop the contact_name column

In [ ]:
# Reorder the columns

In [ ]:
# Check the datatypes one more time before exporting as CSV file.

In [ ]:
# Export the DataFrame as a CSV file. 
# contacts_df_clean.to_csv("Resources/contacts.csv", encoding='utf8', index=False)